story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story9.urls'))
]

story9/urls.py
from django.urls import path
from .views import index, data, addLike, top5books

app_name = 'story9'

urlpatterns = [
    path('', index, name='index'),
    path('data/', data, name='data_books'),
    path('addLike/', addLike, name='add_like'),
    path('top5books/', top5books, name='top5books')
]

story9/models.py
from django.db import models

# Create your models here.
class Book (models.Model):
    id =  models.CharField(max_length = 200, primary_key = True)
    cover = models.CharField(max_length = 100)
    title = models.CharField(max_length = 100)
    author = models.CharField(max_length=100, blank=True)
    publisher = models.CharField(max_length = 100)
    likes = models.IntegerField(default=0)

story9/views.py
from django.shortcuts import render
from django.http import JsonResponse
import json
import requests
from .models import Book
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
def index(request):
    return render(request, 'index.html')

def data(request):
    try:
        q = request.GET['q']
    except:
        q = 'quilting'
    json_response= requests.get("https://www.googleapis.com/books/v1/volumes?q=" + q).json()

    for i in json_response['items']:
        try:
            book = Book.objects.get(id=i['id'])
            likes = book.likes
        except:
            likes = 0
        i['volumeInfo']['likes'] = likes

    return JsonResponse(json_response)

@csrf_exempt
def addLike(request):
    data_books, created = Book.objects.get_or_create(
        id = request.POST['id'],
        cover = request.POST['cover'],
        title = request.POST['title'],
        author = request.POST['author'],
        publisher = request.POST['publisher'],
    )
    data_books.likes=int(request.POST['likes'])
    data_books.save()
    return JsonResponse(data_books.likes, safe=False)

def top5books(request):
    book = Book.objects.order_by('-likes')[:5]
    lst = []
    for i in book:
        lst.append({
            'id' : i.id,
            'cover' : i.cover,
            'title' : i.title,
            'author' : i.author,
            'publisher' : i.publisher,
            'likes' : i.likes
        })

    data = {
        'top5books' : lst
    }
    return JsonResponse(data, safe=False)

story9/templates/index.html
{% load static %}
<html>
    <head>
        <title>
            Book Search - Johanes M P Simarmata
        </title>
        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>    
        <script src="{% static 'story9.js' %}"></script>
        <script src="{% static 'jquery-3.5.0.min.js' %}"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <style>
            body{
                background-image: url('https://s1.1zoom.me/b5050/60/USA_Parks_Mountains_Sky_Haleakala_National_Park_515452_2560x1440.jpg');
                background-repeat: no-repeat;
                background-size: 100% 100%;
                background-attachment: fixed;
                overflow: auto;

            }
            .judul{
                color:white; 
                font-family: 'Droid serif', serif; 
                font-size: 36px; 
                font-weight: 700; 
                font-style: italic; 
                line-height: 44px; 
                margin: 0 0 12px; 
                text-align: center; 
            }
            input[type=text] {
                width: 100%;
                align-items: center;
                box-sizing: border-box;
                border: 2px solid #ccc;
                border-radius: 4px;
                font-size: 16px;
                background-color: white;
                background-repeat: no-repeat;
                padding: 12px 20px 12px 40px;
            }
            tr{
                background-color: aliceblue;
            }
            tr:hover{
                background-color: cornflowerblue;
            }
        </style>

        <script>
            const data_books_url = "{% url 'story9:data_books' %}?q=";
            const top_book_url = "{% url 'story9:top5books' %}";
            const addLike_url = "{% url 'story9:add_like' %}";
        </script>
    </head>
    <body>
        <div class="container">
            <div class="judul pt-3">Book Search by Johanes</div>
            <input type="text" placeholder="Search for you favorite book here" title="Type in the title" class="align-items-center" name="search_box">
            <button type="button" id="input" class="btn btn-success" name="search_submit">Search Now!</button>
            <!-- Button trigger modal -->
            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal" id="modalbutton" name="namebutton">
                Top 5 Books Here!
            </button>
  
            <!-- Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Top 5 Books:</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        </div>
                        <div class="modal-body" id="top5books"></div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>
            
            <table class="table mt-5">
                <thead class="thead-light">
                  <tr>
                    <th scope="col" class="align-middle">No</th>
                    <th scope="col" class="align-middle">Book Cover</th>
                    <th scope="col" class="align-middle">Title</th>
                    <th scope="col" class="align-middle">Authors</th>
                    <th scope="col" class="align-middle">Publisher</th>
                    <th scope="col" class="align-middle">Tombol Like</th>
                    <th scope="col" class="align-middle">Jumlah Like</th>
                    <th scope="col" class="align-middle">Books ID</th>
                  </tr>
                </thead>
                <tbody id="konten"></tbody>
            </table>
            
        </div>
    </body>
</html>